### ISSUE TITLE
Double check license

### ISSUE THREAD

**Issue by orrmany** [orrmany/BlueAnt#1]
@cujomalainey, @rtgree01: As there seems to be a need, I started to prepare eventual publication of my ANT+ code as a separate "library". Please review the licensing terms, especially you, @rtgree01, as I proudly copied ("stealed") many lines of code from you. Curtis, please note this attempt is in no way intended to be a competitor to your library. I just want to make my work available "as-is".  If you find anything useful here, then please use it!
Thanks

**Comment by cujomalainey** [comment]
No worries :) I understand my library will not fit all paradigms so I always welcome alternatives.

**Comment by orrmany** [comment]
Got answer from Ryan in private mail, closing this issue:

Ryan <[EMAIL.DELETED.FOR.PRIVACY> ezt írta (időpont: 2020. máj. 7., Cs, 5:41):
Yes.. I approve... and good luck!

Sent with ProtonMail Secure Email.
