### ISSUE TITLE
Error within sdant.cpp

### ISSUE THREAD

**Issue by drewvigne** [orrmany/BlueAnt#2]
I've finally had time to play around with the example. It compiles and flashes successfully only when I comment out line 147 on the sdant.cpp source file. 

147: `Bluefruit.setMultiprotocolSemaphore(&_ant_event_sem);`

When compiling with this line included I receive the following error: 
`src\sdant.cpp:147:13: error: 'class AdafruitBluefruit' has no member named 'setMultiprotocolSemaphore'` 

which is obviously because the class does not contain the setMultiprotocolSemaphore member. I cannot seem to find any clues as to what to do to resolve this issue. If anyone has ideas I would love to hear your advice. I'll continue to investigate but so far I've had no luck.

**Comment by drewvigne** [comment]
Closed. Issue was due to an error within my directories.

**Comment by drewvigne** [comment]
Successfully flashed the build to my itsybitsy adafruit. Tested with Garmin HR Monitor and it worked. Amazing that this code was able to transform the BLE device into ANT+. I'll be working on implementing the power profile in the coming weeks.

**Comment by orrmany** [comment]
Hi Drew,

Sorry, I've completely missed your mail 7 days ago. :( I apologize.

On the other hand, I am happy.that you have been able to solve the problem.

Good luck for the power profile. Should I have a power meter, I would have
worked on that, too.

Br, Gabor

**Comment by orrmany** [comment]
@drewvigne , I would welcome a pull-request for power profile eventually :)
